VISION360 = {
    "id": "vision360",
    "title": "Vision 360°",
    "icon": "&#127760;",
    "color1": "#0008CF",
    "color2": "#3B3BFF",
    "definition": "Déployer un projet d\u2019IA, c\u2019est bien plus que de la technique. Ce module présente les 8 enjeux à anticiper pour une mise en \u0153uvre responsable et maîtrisée de l\u2019IA générative.",
    "hook": "88\u00a0% des organisations utilisent l\u2019IA en production, mais seulement 18\u00a0% disposent d\u2019un cadre de gouvernance complet. Ce parcours vous donne les clés pour combler cet écart.",
    "counters": [("8", "", "enjeux à maîtriser"), ("3", "", "règles de sécurité École Numérique"), ("5", "", "principes éthiques")],
    "enjeux_cards": [
        ("Éthique", "#8E44AD", "S\u2019assurer que l\u2019IA est utilisée sans préjudice ni discrimination. Lié aux enjeux Juridique et RH."),
        ("Juridique", "#2980B9", "Garantir le respect du RGPD, de l\u2019AI Act et du Code du travail. Lié aux enjeux Éthique et Sécurité."),
        ("Ressources Humaines", "#E67E22", "Préserver l\u2019expertise métier et maintenir l\u2019humain au centre. Lié aux enjeux Changement et Éthique."),
        ("Conduite du changement", "#16A085", "Accompagner l\u2019adoption avec méthode (ADKAR). Lié aux enjeux RH et UX."),
        ("Données", "#3498DB", "La qualité des données détermine la qualité de l\u2019IA. Lié aux enjeux Sécurité et UX."),
        ("Sécurité", "#C0392B", "Protéger les données et les systèmes (3 règles de l\u2019École Numérique). Lié aux enjeux Juridique et Données."),
        ("Design UX", "#E74C3C", "Concevoir des interfaces accessibles et calibrer la confiance. Lié aux enjeux Changement et Données."),
        ("Environnement", "#27AE60", "Maîtriser l\u2019empreinte carbone de l\u2019IA. Lié aux engagements RSE."),
    ],
    "interdependances": [
        ("Éthique", "Juridique"),
        ("Sécurité", "Données"),
        ("RH", "Conduite du changement"),
        ("UX", "Données"),
        ("Éthique", "RH"),
        ("Sécurité", "Juridique"),
    ],
    "quiz": [
        {"q": "Un chatbot interne donne des réponses contradictoires sur les congés. Quel enjeu est principalement concerné\u00a0?", "opts": ["Éthique", "Données", "UX", "Juridique"], "correct": 1, "expl_ok": "Exact\u00a0! C\u2019est un problème de qualité du corpus de données (deux versions du document coexistent). L\u2019enjeu Données est le premier concerné.", "expl_ko": "C\u2019est l\u2019enjeu Données. Les réponses contradictoires viennent d\u2019un corpus mal géré (doublons, versions obsolètes).", "theme": "Données"},
        {"q": "Un collègue colle un PV de CSE dans ChatGPT pour en faire un résumé. Quel enjeu est concerné en priorité\u00a0?", "opts": ["Environnement", "Sécurité", "UX", "Changement"], "correct": 1, "expl_ok": "Exact\u00a0! C\u2019est une violation de la règle n°2 (protéger les données confidentielles). Les données envoyées à ChatGPT peuvent être réutilisées.", "expl_ko": "C\u2019est l\u2019enjeu Sécurité. Un PV de CSE contient des données confidentielles qui ne doivent jamais être envoyées à un LLM externe.", "theme": "Sécurité"},
        {"q": "L\u2019équipe de maintenance résiste au déploiement d\u2019un nouvel outil IA. Quel enjeu est concerné\u00a0?", "opts": ["Sécurité", "Éthique", "Conduite du changement", "Données"], "correct": 2, "expl_ok": "Exact\u00a0! La résistance au changement est au c\u0153ur de l\u2019enjeu Conduite du changement. Il faut expliquer le pourquoi avant le comment (ADKAR).", "expl_ko": "C\u2019est la Conduite du changement. La résistance est naturelle et doit être accompagnée avec méthode.", "theme": "Changement"},
        {"q": "Un outil IA de tri de CV défavorise systématiquement les candidats seniors. Quels enjeux sont concernés\u00a0?", "opts": ["Éthique et Juridique", "Données et UX", "Environnement et Sécurité", "Changement et RH"], "correct": 0, "expl_ok": "Exact\u00a0! C\u2019est un problème éthique (discrimination par biais de proxy) ET juridique (non-conformité au Code du travail et potentiellement à l\u2019AI Act).", "expl_ko": "Ce sont les enjeux Éthique (discrimination algorithmique) et Juridique (non-conformité au droit du travail et à l\u2019AI Act).", "theme": "Interdépendances"},
    ],
    "profils": [
        ("Chef de projet / MOA", "Parcours complet\u00a0: les 8 modules pour une vision 360° de tous les enjeux."),
        ("Direction Juridique", "Priorité\u00a0: modules Juridique + Éthique + Sécurité."),
        ("Direction RH", "Priorité\u00a0: modules RH + Changement + Éthique."),
        ("Direction Technique / DSI", "Priorité\u00a0: modules Sécurité + Données + Environnement."),
        ("Direction Communication", "Priorité\u00a0: modules UX + Éthique + Changement."),
        ("Tout collaborateur", "Commencez par les modules Éthique et Sécurité, qui posent les bases essentielles."),
    ],
}
